### ISSUE TITLE
Impliement Threading

### ISSUE THREAD

**Issue by SteveCossy** [SteveCossy/IOT#12]
References:
  https://realpython.com/intro-to-python-threading/
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path

**Comment by shermp** [comment]
Hi Steve.

What are you actually seeking to achieve? I'm a bit confused.

**Comment by SteveCossy** [comment]
OK - time to explain ...
Recent hardware enhancements from Mr Hornblow mean more data coming from the host computer on the gateway, as opposed to coming from sensors.  Current list (from off top of my head, but I might edit it later):
* CPU Temperature
* Ambient temperature in gateway PC box
* Client status (need to think about how to use this more - currently 0=normal, -1=receive error)
The temperature readings have nothing to do with the sensors, unless they get so high that the sensor readings are no longer processed.  They should be checked at a set frequency (perhaps every five minutes?).

Seems to me there are three different things going on here:
* Reading incoming sensor data.  Processed on demand.
* Reading data local to the gateway computer (as above). Processed periodically or on demand.
* Sending data to a cloud for processing. Processed on demand.

Currently all three functions are handled in one piece of code - in lines 126 to 134 at time of writing: https://github.com/SteveCossy/IOT/blob/master/LoRaReAd/LoRa_to_MQTT.py
Given the discussions above, it would seem a good idea to separate out these three things.

The first thought was to use a queue.  That was tried briefly, then abandoned, as outlined here: https://github.com/SteveCossy/IOT/issues/10
Next idea is that perhaps, as this is a relatively simple requirement, a thread might be more appropriate.
That to us to this issue ... and trying a thread-based solution!

**Comment by shermp** [comment]
Hmm, yeah, threading could work. I've never tried threading in python, so unsure of exactly how it should work.

The main concern one has to worry about is data sharing. In this case, it looks like you won't have multiple threads trying to update the same data, so it should be fairly straightforward.

**Comment by SteveCossy** [comment]
A few hours today, and it seems to be running well in my test-bed: https://github.com/SteveCossy/IOT/blob/master/test/Parse-iwlist.py

**Comment by SteveCossy** [comment]
Done, but this identified the need for more flexible Cayenne data types.
Ref: https://github.com/SteveCossy/IOT/issues/14
