### ISSUE TITLE
Implement some error handling

### ISSUE THREAD

**Issue by SteveCossy** [SteveCossy/IOT#8]
Time to add some error checking.  First priority is to raise an exception if a packet turns up in a serial stream in https://github.com/SteveCossy/IOT/blob/master/LoRaReAd/LoRa_to_MQTT.py
Plan is to send a special packet to Cayenne and to a local CSV file containing an error number.
Initial research:
C error numbers.  Are these available in Python? http://c-for-dummies.com/blog/wp-content/uploads/2016/01/errno.txt
Custom Exception.  Is this how I should do it? https://dbader.org/blog/python-custom-exceptions
General handling notes: https://docs.python.org/3/tutorial/errors.html & https://docs.python.org/3/library/exceptions.html#Exception

**Comment by shermp** [comment]
Just quickly before bed:

Yeah, doing some error handling might not be a bad idea!

I would personally avoid reusing the C error numbers. Because they are actually system error numbers, used by system calls. Some people do use them, but I tend to find that they never quite fit the actual error. Also, they aren't portable. Probably easiest to define your own error numbers/codes. If you really want to use them though, they are available with [errno](https://python.readthedocs.io/en/latest/library/errno.html).

That's how you do exceptions yes.

**Comment by SteveCossy** [comment]
Notes from Andrew Hornblow 08:16 (2 hours ago)
Standard Diagnostics:
Suggest:
1/. The 'QoS' or hor good the data is comes in on Channel 25 / 'Y' at present.
Recommend that we use this channel in a kind of hybrid way...
- Normal operation is x% good data typically 60 to 100% based on the Bad x Good / 100 ( in last 10 minutes or an hour )
IF falls to a low value  then the number or RAW packets unsuccessfully processed
IF no data and or a serial timeout then the data falls back to a single digit code that could represent:
 - The number of timeouts in the last x minutes
IF the com port does not even appear to be present or able to be opened then:
 - Return a '0'
This seems a little logical as it covers a host of typical network issues.  The 'normal' 100% I would expect for 99% of the time with LoRa may as well be logical considering:
- ASK modules will be in use for a lot of cheap approaches (breadboards in butter boxes spread around a school room / grounds / possum traps)
- 'Glance-able' www / browser single system digit diagnostic that has depths of quality of meaning without having to start ssh'ing into anything etc

**Comment by SteveCossy** [comment]
OK - Sherman says make up our own error codes (I really like that), Andrew suggests some possible contenders.
Methinks the answer might be a toml file.  Human readable and editable, with comments describing errors as required, and can easily be read into a dictionary are required.

**Comment by SteveCossy** [comment]
Initial error function created with some logging, to get started.  Informs issue 9 (which has comments and examples) https://github.com/SteveCossy/IOT/issues/9.
Long way from something long-term!

**Comment by SteveCossy** [comment]
Some more references ...
https://docs.python.org/2/library/traceback.html
https://docs.python.org/2/library/errno.html
https://docs.python.org/2/library/sys.html#sys.last_type
https://stackoverflow.com/questions/12283377/are-python-error-numbers-associated-with-ioerror-stable

**Comment by SteveCossy** [comment]
Playing about with try: except
```
>>> try:
...   print ( 1/0 )
... except:
...   print ('start')
...   Err = traceback.print_exc()
...   print ( Err )
...   print ('end')
...
start
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
None
end
```
Something to play with ...

**Comment by SteveCossy** [comment]
@shermp 
The logging is now a little serious.  Can't say I'm particularly proud of the code, but it does do three things when an exception occurs:
* Outputs the traceback into a file 'LOG_<script name>'
* Writes an entry into a error CSV, containing the timestamp, device id, and script name
* Sends a status flag to Cayenne, with a number less than 0 (currently -1)
  Cayenne has a trigger set to email me if this happens
https://github.com/SteveCossy/IOT/commit/5322cda8ff87f7aa439d0e54c71fee302a24c237
As always, comments welcome.  There is a lot that could be done still.

Cheers!   Steve

**Comment by SteveCossy** [comment]
Updated and implemented old bash script to start and restart the python script as required.
https://github.com/SteveCossy/IOT/commit/7e34faa01c902e639a34dd612e42a109ee6d1202
Tested - all good!  :-)
