### ISSUE TITLE
Structure incoming serial data so some complexity can be added to processing

### ISSUE THREAD

**Issue by SteveCossy** [SteveCossy/IOT#9]
Currently https://github.com/SteveCossy/IOT/blob/master/LoRaReAd/LoRa_to_MQTT.py simply reads 7 bytes from the serial port.  We don't know if this is a problem, because there is no error reporting (just rudimentary checking, which drops a packet without a trace).  https://github.com/SteveCossy/IOT/issues/8 will determine whether packets are being dropped because input is not aligning with a packet boundary (or some other reason).
Perhaps a queue is the way to do this? https://docs.python.org/3/library/queue.html

**Comment by shermp** [comment]
I'm wondering if the traditional serial method of packet 'framing' might be the way to go. Instead of blindly reading seven packets at a time (good luck if you get out of sync!), instead read packets until you reach a line terminator (typically `\n` or `\r\n`. Once you've read in bytes up to the line terminator, test the payload size, and if correct, do the checksum test etc.

**Comment by shermp** [comment]
In general, I think having a sync footer is easier than a sync header, especially for unstable connections. Much easier to look back and see what you got, rather than trying to predict what you are supposed to receive in the future.

**Comment by SteveCossy** [comment]
OK - we have some data to think about.
Seems that when the LoRa module gets an error in the data, it sends the text 'rx error' to its host device.  This seems to be caused by a sensor with low battery so far.  That puts it out of sync, and it keeps out of sync until a character greater than 128 gets where the code expects the 'Channel' letter.  Result is
```
Traceback (most recent call last):
  File "/home/pi/IOT/LoRaReAd/LoRa_to_MQTT.py", line 85, in <module>
    Channel = str(Channel,'ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 0: ordinal not in range(128)
```
Options:
- Do nothing.  Not helpful here.
- Report the error, reset the read buffer, and continue.
- Capture errors in the data decoding lines
```
 # Data processing
       head1,head2,Device,Channel,Data,Cks=struct.unpack("<ccccHB",PacketIn)
       Channel = str(Channel,'ASCII')
```
- Shut down the program whenever there is an error, and have a bash script that notes this, and restarts it.
- Other things???

I'll have another look at this later in the day.  In the meantime I'm leaving it with just one sensor running.
:-)

[screen+errorLog-20200119.zip](https://github.com/SteveCossy/IOT/files/4083472/screen%2BerrorLog-20200119.zip)

**Comment by SteveCossy** [comment]
Got everything going to a reasonable standard using readuntil as suggested by @shermp
